from setuptools import setup

setup(
	name='AbstractAI',
	version='0.1.0',
	author='Charlie Angela Mehlenbeck',
	author_email='charlie_inventor2003@yahoo.com',
	packages=['AbstractAI'],
	py_modules=[],
	scripts=[],
	url='https://github.com/inventor2525/AbstractAI',
	license='LICENSE',
	description='A simple library to abstract various ML models.',
	long_description=open('README.md').read(),
	install_requires=[
		'numpy',
		'torch>=2.0.1',
		'numexpr>=2.8.4',
		'transformers',
		'bitsandbytes',
		'einops',
		'accelerate',
		'xformers',
		'scipy',
		'sentencepiece',
		'openai-whisper',
		'datasets',
		'soundfile',
		'nltk',
		'PyQt5', #Note: may need to be run like this, to handle the case where stuck when installing (happened on pinephone) and can't accept license even in verbose:   pip install pyqt5 --config-settings --confirm-license= --verbose
		'sounddevice',
		'pydub',
		'evdev',
		'pyperclip',
		'pyautogui',
        'pexpect',
		'tzlocal',
		'llama-cpp-python',
		'openai',
		'auto-gptq',
		'optimum',
	],
	python_requires='~=3.10'
)
